### ISSUE TITLE
Does asd0, asd1, asd2 means the  tortuosity in x,,y,z direction of the  3D image

### ISSUE THREAD

**Issue by 007craig** [PMEAL/pytrax#18]
Hi all,

I have one question related to direction-dependent tortuosity. I calculated tortuosity using 3D image. It gives me msd  tortuosity, asd0 tortuosity, asd1 tortuosity, asd2 tortuosity, my question is does asd0, asd1, asd2 means the  tortuosity in x,,y,z direction of the  3D image? It bothers me a lot and it would be great if this question can be solved. Thanks a lot！

Wenhui

**Comment by TomTranter** [comment]
Yep
